### ISSUE TITLE
Calling Kernel#require in a rescue block after a failed require panics

### ISSUE THREAD

**Issue by lopopolo** [lopopolo/ferrocarril#115]
The following code results in an 'already borrowed: BorrowMutError'

```ruby
def fail
  begin
    require 'foo'
  rescue LoadError
    require 'forwardable'
  end
end
fail
```

```
thread 'main' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: rust_begin_unwind
             at src/libstd/panicking.rs:309
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/d132f544f9d74e3cc047ef211e57eae60b78e5c5/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::expect
             at /rustc/d132f544f9d74e3cc047ef211e57eae60b78e5c5/src/libcore/result.rs:827
  12: core::cell::RefCell<T>::borrow_mut
             at /rustc/d132f544f9d74e3cc047ef211e57eae60b78e5c5/src/libcore/cell.rs:871
  13: <alloc::rc::Rc<core::cell::RefCell<mruby::state::State>> as mruby::eval::MrbEval>::push_context
             at mruby/src/eval.rs:153
  14: mruby::extn::core::kernel::Kernel::require_impl
             at mruby/src/extn/core/kernel.rs:113
  15: mruby::extn::core::kernel::Kernel::require
             at mruby/src/extn/core/kernel.rs:139
  16: mrb_vm_exec
             at ./mruby-sys/vendor/mruby-c078758/src/vm.c:1466
  17: mrb_vm_run
             at ./mruby-sys/vendor/mruby-c078758/src/vm.c:974
  18: mrb_top_run
             at ./mruby-sys/vendor/mruby-c078758/src/vm.c:2862
  19: mrb_load_exec
             at ./mruby-sys/vendor/mruby-c078758/mrbgems/mruby-compiler/core/parse.y:6192
  20: mrb_load_nstring_cxt
             at ./mruby-sys/vendor/mruby-c078758/mrbgems/mruby-compiler/core/parse.y:6214
  21: <alloc::rc::Rc<core::cell::RefCell<mruby::state::State>> as mruby::eval::MrbEval>::eval
             at mruby/src/eval.rs:108
  22: mruby_bin::repl::run
             at ./mruby-bin/src/repl.rs:121
  23: rirb::main
             at mruby-bin/src/bin/rirb.rs:8
  24: std::rt::lang_start::{{closure}}
             at /rustc/d132f544f9d74e3cc047ef211e57eae60b78e5c5/src/libstd/rt.rs:64
  25: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  26: std::panicking::try::do_call
             at src/libstd/panicking.rs:294
  27: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  28: std::panicking::try
             at src/libstd/panicking.rs:273
  29: std::panic::catch_unwind
             at src/libstd/panic.rs:388
  30: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  31: std::rt::lang_start
             at /rustc/d132f544f9d74e3cc047ef211e57eae60b78e5c5/src/libstd/rt.rs:64
  32: rirb::main
Illegal instruction: 4
```

**Comment by lopopolo** [comment]
The following code also panics in the REPL:

```console
>>> require 'foo'
Backtrace:
    (rirb):1: cannot load such file -- foo (LoadError)
    (rirb):1
>>> require 'forwardable'
```

**Comment by lopopolo** [comment]
This was fixed by GH-116.
